#
#            Makefile for UNIX systems
#            using a GNU C complier
#
# Compiler flags:
#    -g    -- Enable debugging
#    -Wall   -- Turn on all warnings
#

all:
	@echo "build, run, clean"
build:
	gcc -g -Wall -orectangle_area_perimeter rectangle_area_perimeter.c
run:
	./rectangle_area_perimeter
clean:
	rm -f rectangle_area_perimeter