# Makefile for UNIX systems
# using a GNU C compiler
#
# Compiler flags:
#    -g     -- Enable debugging
#    -Wall  -- Turn on all warnings

all:
	@echo "build, run, clean"
build:
	gcc -g -Wall -oprint_hello print_hello.c
run:
	./print_hello
clean:
	rm -f print_hello